### ISSUE TITLE
Cannot "make install"

### ISSUE THREAD

**Issue by Starcr0ss** [MartinF99/PlastikStyle#13]
When I run `make install` after doing all the other steps in the readme, I get the following error.
`make: *** No rule to make target 'install'.  Stop.`
I don't know what I am doing wrong. I am on Debian 12 and only want to install the qt5 version

**Comment by MartinF99** [comment]
Did you run cmake first?

**Comment by MartinF99** [comment]
Sorry I just read you did all the other steps. In the build directory there should be a a makefile, can you attach that

**Comment by MartinF99** [comment]
Or try to run cmake with -DCMAKE_INSTALL_PREFIX=/usr
so basically cmake -DENABLE_ALL=off -DENABLE_QT5 -DCMAKE_INSTALL_PREFIX=/usr

**Comment by MartinF99** [comment]
and then attempt to run make and make install

**Comment by MartinF99** [comment]
Any news on this?

**Comment by Starcr0ss** [comment]
Okay so the command I used to get back to the `make install` part was
`cmake -DENABLE_ALL=off -DENABLE_QT5=off -DCMAKE_INSTALL_PREFIX=/usr ../`
When I run `make install` I get:
`make: *** No rule to make target 'install'.  Stop.`

Here is the [Makefile.txt](https://github.com/MartinF99/PlastikStyle/files/14809515/Makefile.txt)

**Comment by MartinF99** [comment]
Ah I see what's happening DENABLE_ALL disables both qt5 and qt6 so to build qt6 only you need to also call DENABLE_QT6=on

**Comment by MartinF99** [comment]
So the full call would be `cmake -DENABLE_ALL=off -DENABLE_QT6=on -DCMAKE_INSTALL_PREFIX=/usr ../`

**Comment by Starcr0ss** [comment]
Okay so now I'm getting a new error that may have to do with the fact that I am on Debian 12 which is not really made with Qt6 in mind:
```
CMake Error at qt6/QStyle/CMakeLists.txt:1 (find_package):
  Could not find a package configuration file provided by "Qt6" with any of
  the following names:

    Qt6Config.cmake
    qt6-config.cmake

  Add the installation prefix of "Qt6" to CMAKE_PREFIX_PATH or set "Qt6_DIR"
  to a directory containing one of the above files.  If "Qt6" provides a
  separate development package or SDK, be sure it has been installed.
```
If I did something like `sudo apt install qt6`
I would just get `E: Unable to locate package qt6`
Not really seeing the need to have Qt6 when I specifically am asking to exclude that part

**Comment by Starcr0ss** [comment]
That worked! But now it seems I only have it for qt6? Nothing for qt5 and nothing shows up in my plasma settings. I sense we're very close...

**Comment by MartinF99** [comment]
Oh I thought that was your intention. To install for both qt5 and qt6 simply call 
`cmake -DCMAKE_INSTALL_PREFIX=/usr ../' 
DENABLE_ALL option is on by default and adds both qt5 and qt6

**Comment by MartinF99** [comment]
also you need the qt5-base-dev package

**Comment by Starcr0ss** [comment]
> Oh I thought that was your intention. To install for both qt5 and qt6 simply call `cmake -DCMAKE_INSTALL_PREFIX=/usr ../' DENABLE_ALL option is on by default and adds both qt5 and qt6

Well I only wanted Qt5 actually - nothing of Qt6. But both is definitely an option and we ignore the 6 since it has no use to me

**Comment by MartinF99** [comment]
oh then its `cmake -DENABLE_ALL=off -DENABLE_QT5=on -DCMAKE_INSTALL_PREFIX=/usr ../ ' also you need the package qtbase5-dev

**Comment by MartinF99** [comment]
I figured that with the cmake call you gave me (with the option -DENABLE_QT5=off)  you wanted to turn off qt5 styling.

**Comment by Starcr0ss** [comment]
> oh then its `cmake -DENABLE_ALL=off -DENABLE_QT5=on -DCMAKE_INSTALL_PREFIX=/usr ../ ` also you need the package qtbase5-dev

There we go! Successfully installed and I see it in plasma settings! Thanks so much for your help!
