### ISSUE TITLE
Text inside progress bars do not follow color scheme when using a dark color scheme

### ISSUE THREAD

**Issue by hazel-bunny** [MartinF99/PlastikStyle#3]
How to reproduce:
1. Set Application Style to plastik
2. Set color scheme to breeze dark
3. Open any app with a progress bar, eg dolphin

Observed result:
Text is black

Expected result:
Text should be #fcfcfc as stated in the color scheme

I'll upload a screenshot once I get one that doesn't expose my personal info

**Comment by MartinF99** [comment]
The progressbar label text is drawn either using the text colour or the "base" colour, ( as defined by QPalette) so this might be intended behaviour, (that code is taken from QtStylePlugins, I'll have to look to make that work) But the theme isn't designed with a dark colourscheme in mind anyway. (you notice that e.g. button highlight effects are dark, (as button().color().darker() is used to make highlights in plastik

**Comment by MartinF99** [comment]
Oh I should probably add that when the label is over the highlight on the progressbar groove, than base colour is used, otherwise it should be the text colour.

**Comment by MartinF99** [comment]
So I replaced the ProgressbarLabel colour with HighlightedText if it's over the Highlighted part of the groove, can you check if that fixes your issue? (You'll have to build from git)
