### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by hazel-bunny** [MartinF99/PlastikStyle#5]
Hi, I'm trying to package this style for Fedora in my COPR. Here is a [list of what can be built in COPR](https://docs.pagure.org/copr.copr/user_documentation.html#what-i-can-build-in-copr). As this project does not include a license, it is not clear whether it can be built there. Please include a license, preferably something like GNU LGPL or GNU GPL used by KDE.

**Comment by MartinF99** [comment]
So I've added the LGPL-v2.1 as the original code (QPlastiquestyle from Qt Styleplugins) was licensed under that as well. (And this is a fork of QPlastiquestyle)

**Comment by MartinF99** [comment]
Because of the weird Qt Dual-triple licensing thing of qt, I'm not quite sure if this is the correct license choice, so I'm keeping this open for now.

**Comment by MartinF99** [comment]
Considering there aren't any further comments, I'll close this issue again. And consider it done
