### ISSUE TITLE
Icons in context menus are misaligned

### ISSUE THREAD

**Issue by 2xsaiko** [MartinF99/PlastikStyle#6]
Menus when using this theme draw the icons offset to the top left and cut off (here in Dolphin). Encountered this in qtstyleplugins originally which is why I switched to this.

Might be a HiDPI/screen scale thing?

![image](https://github.com/MartinF99/PlastikStyle/assets/3987560/4620eff5-9eff-43f9-8c87-b709b8963352)

plastikstyle 1.0.2

Operating System: NixOS 23.11
KDE Plasma Version: 5.27.6
KDE Frameworks Version: 5.108.0
Qt Version: 5.15.9
Kernel Version: 6.1.38 (64-bit)
Graphics Platform: Wayland
Processors: 24 × 13th Gen Intel® Core™ i7-13700F
Memory: 62.7 GiB of RAM
Graphics Processor: AMD Radeon RX 6800 XT

**Comment by MartinF99** [comment]
ok I've not encountered this, can you tell me the scale factor you use?

**Comment by MartinF99** [comment]
Yes I believe, that this has to do with some offsets being hardcoded (and clearly not created with HiDPI in mind). I will look on how styles like fusion fix this issue and try to implement something similar

**Comment by 2xsaiko** [comment]
1.5x scale factor (though it also happens on the other monitor which has 1x scale factor). Thanks!

**Comment by MartinF99** [comment]
So I don't have that issue, but I may need to use the devicePixelratios for offset calculations.

**Comment by MartinF99** [comment]
So this is apparently harder than it looked. I even tried to calculate using fusions style code (in places, but it still centres the icons on the top left corner.

**Comment by MartinF99** [comment]
OK so this bug does indeed seem to only happen on Wayland, and X seems unaffected

**Comment by MartinF99** [comment]
So this bug seems to be mostly fixed now, only the active button for checked icons is misaligned now

**Comment by MartinF99** [comment]
Can someone test the code in scaling-support? The sunken rectangle that marks a checked icon will be misaligned though

**Comment by MartinF99** [comment]
This should be fixed now on the master branch, so closing this
